# Dockerfile.base
FROM python:3.14.3-alpine3.23 AS base-builder

RUN apk add --no-cache git build-base

WORKDIR /setup

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip && \
    pip install -r requirements.txt

RUN apk del git build-base
RUN apk cache clean
